export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as NotFound } from './NotFound';
export { default as Banner } from './Banner';
export { default as Button } from './Button';
export { default as Modal } from './Modal';
export { default as MovieSection } from './MovieSection';
export { default as ScrollUp } from './ScrollUp';
export { default as Loading } from './Loading';
